- tyk-hybrid/templates/deployment-gw-repset.yaml
removing development artefact `{{end}}`
> rpcConnString is case sensitive

- values_community_edition.yaml
> Remove the unused gateway.redis section in ce values.yaml

- tyk-pro/configs/tyk_sink.conf
- tyk-pro/templates/configmap-mdcb.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/service-mdcb.yaml
- values.yaml
This change enables the deployment of the master DC in a multicluster MDCB setup of Tyk Enterprise.
> Add templates for MDCB and include in values.yaml

- values_hybrid.yaml
Latest has the update fixes so lets pull that down for now.
> Change hybrid controller tag

- values.yaml
Latest tag has the update fixes so lets make that the default pull for now.
> Change controller tag

- tyk-k8s/Chart.yaml
Needs a bump due to changes in the container command.
> tyk-k8s chart bump

- README.md
Just fixes a few of typos in the README.
> Fixes a few typos in the README

- README.md
Removed sections that didnt make sense - changed some wording and put link to operator at the top of page as well.
> punch up the readme

- tyk-headless/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
This one along with #95 should fix TD-37 ticket
> TD-37 - Pods dont automatically pick up config changes

- .github/kind-cluster-v1.16.15.yml
- .github/kind-cluster-v1.17.17.yml
- .github/kind-cluster-v1.18.15.yml
- .github/kind-cluster-v1.19.7.yml
- .github/kind-cluster-v1.20.2.yml
- .github/kind.yml
- .github/tyk_ce_values.yaml
- .github/tyk_hybrid_values.yaml
- .github/tyk_pro_values.yaml
- .github/workflows/smoke-test.yml
- tyk-hybrid/templates/deployment-gw-repset.yaml
Adds a GitHub Action which runs smoke tests for PRs and master branch. Also, any suggestions on how we could test the hybrid chart?
> [TD-206] Automated smoke tests

- .github/workflows/lint-test.yaml
- ct.yaml
This PR should allow to run additional tests (use --upgrade in ct install to test upgrading charts) and lint every pull request.
> [TD-244] Add lint and tests

- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
This allows things like setting vars from configmaps/secrets/downward api/etc.
> allow more flexible expression of extraEnv

- .gitignore
- README.md
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-headless/templates/secrets-mounts.yaml
- tyk-headless/values.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/secrets-mounts.yaml
- tyk-hybrid/values.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/templates/secret-mounts.yaml
- tyk-pro/templates/secrets-mounts.yaml
- tyk-pro/values.yaml
Add ability to mount files as secrets to all the Tyk stack components in all the charts
> [TD-422] Allow users to mount files as secrets

- tyk-headless/configs/tyk_mgmt.conf
- tyk-pro/templates/_helpers.tpl
remove control port from config, its being set by env file, and unset the dashboard https based off gateway
> Fix dashboard HTTPS and OSS control port hard code

- .github/workflows/smoke-test.yml
- tyk-pro/templates/_helpers.tpl
Smoke-tests are failing on the master for tyk-pro.
> Fix CI Smoke Tests

- .github/workflows/smoke-test.yml
- tyk-headless/templates/_helpers.tpl
- tyk-hybrid/README.md
- tyk-pro/templates/_helpers.tpl
remove debug statement since all tests are passing now.
> [BUG] fix smoke tests

- tyk-headless/templates/_helpers.tpl
- tyk-hybrid/templates/_helpers.tpl
- tyk-pro/templates/_helpers.tpl
Fixing issue: https://github.com/TykTechnologies/tyk-helm-chart/issues/139
> Fix adding unnecessary new line to the end of entries

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
https://tyktech.atlassian.net/browse/TD-536
> TD-536 - Fix bug in tyk-headless

- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-tib.yaml
> Fix or logic

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
Add the ability to change the gateway strategy
> add-ability-to-modify-strategy

- tyk-pro/scripts/init.sh
See https://github.com/TykTechnologies/tyk-helm-chart/issues/175 for more details
> Fix command in init script to wait for dashboard readiness

- tyk-pro/templates/secrets-mounts.yaml
> Fix secrets mounts

- .gitignore
- charts/tyk-pump/.helmignore
- charts/tyk-pump/Chart.yaml
- charts/tyk-pump/README.md
- charts/tyk-pump/conf/pump.conf
- charts/tyk-pump/docs/docs.yaml
- charts/tyk-pump/templates/NOTES.txt
- charts/tyk-pump/templates/_helpers.tpl
- charts/tyk-pump/templates/configmap.yaml
- charts/tyk-pump/templates/deployment.yaml
- charts/tyk-pump/templates/hpa.yaml
- charts/tyk-pump/templates/secrets.yaml
- charts/tyk-pump/templates/service.yaml
- charts/tyk-pump/values.yaml
This is PR implement stand-alone Tyk Pump Helm Chart.
> [TD-546] Tyk Pump Helm chart

- tyk-headless/templates/ingress-gw.yaml
- tyk-headless/values.yaml
Updated Ingress resource template to support latest Kubernetes API versions with backward compatibility also.
> [TD-597] Updated Ingress resource to support various Kubernetes versions

- README.md
- tyk-pro/scripts/bootstrap.sh
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/values.yaml
This pull request enables the helm charts users to correctly deploy the tyk helm charts using TLS.
> Bootstrap TLS fix

- .github/workflows/release-charts.yaml
Added Github Action which release helm charts when a version tag is created.
> [TT-5731] Added GithubAction to release helm chart

- tyk-pro/templates/deployment-dash.yaml
`TYK_DB_STORAGE_MAIN` environment variables were introduced in Dashboard v4 and doesn't work with older version.
This PR replaces these environment variables with the ones supported across all versions.
[TT-6193](https://tyktech.atlassian.net/browse/TT-6193)
While installing Dashboard version less than v4, MongoURL was not getting set.
Testing following scenarios
- Dashboard and Pump works with v4
- Dashboard and Pump works with v3.2.1
> [TT-6193] Fixed Env variables used for mongo configuration

- CHANGELOG.md
- tyk-headless/values.yaml
There are 3 proposed changes:
* Clarify the settings required between *Redis*, *Redis Sentinel* and *Redis Cluster*
* Add examples explicitly for *Redis Sentinel*
* Change default for `enableCluster` to `false` to align with Bitnami Redis chart (`bitnami/redis`) [Potential Breaking Change]
The latter could be a breaking change, however the `bitnami/redis` chart used in the documentation does not run as a cluster, therefore this proposal aligns with the documentation (https://tyk.io/docs/tyk-oss/ce-helm-chart/).  However, the documentation also references a "Redis Cluster" address so there is an inconsistency.  The choice is to either change the documentation to reflect a *Redis Cluster* (e.g. `bitnami/redis-cluster`) or use the existing Bitnami Redis chart (`bitnami/redis`) but then …
> Clarify Redis Options and Update Defaults

- CHANGELOG.md
- tyk-pro/templates/deployment-dash.yaml
Increased `initialDelaySeconds` of Dashboard probes.
[TT-6242](https://tyktech.atlassian.net/browse/TT-6242)
Dashboard installation fails on Mac machine if postgres is used as data store.
Tested Pro installation on linux machine.
> [TT-6242] Increased `initialDelaySeconds` of Dashboard probes

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-headless/values.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/values.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/values.yaml
Added `securityContext` field for every component(Gateway, Dashboard, Pump, MDCB, TIB) in values.yaml file.
It is used to set PodSecurityContext field of corresponding deployments.
[TT-5702](https://tyktech.atlassian.net/browse/TT-5702)
Resolves #178 
helm charts failed to installed in OpenShift environment because securityContext values were hard-coded and OpenShift has securityContext constraints which requires UserID/fsGroup to be within specific range. 
Since securityContext is configurable user can easily install helm charts using those values.
Tested following on both OpenShift and non-OpenShift environment
1. Tyk-Pro successfully installed with and without custom securityContext values.
2. Tyk-Headless successfully installed with and without custom securityContext values.
3. …
> [TT-5702] Make security context fields configurable

- .github/workflows/smoke-test.yml
- .github/workflows/tests-pr.yml
- tyk-pro/templates/secrets.yaml
- tyk-pro/templates/statefulset-enterprise-portal.yaml
- tyk-pro/values.yaml
> Add PVC to Enterprise Portal

- tyk-pro/templates/service-dash.yaml
- tyk-pro/templates/service-mdcb.yaml
- tyk-pro/values.yaml
This PR will allow the customers to add annotations to their services. This is required when deploying LoadBalancer types.
https://github.com/TykTechnologies/tyk-helm-chart/issues/230
Required by anyone who would like to deploy these Tyk services as LBs.
> TT-7029 Add ability to manage annotations for the MDCB and Dashboard services

- tyk-pro/templates/deployment-mdcb.yaml
Currently the MDCB is not taking Redis cluster config from the main redis section
> TT-7027 Fix missing MDCB storage config

- tyk-headless/tests/deployment-gw-repset_test.yaml
Signed-off-by: Burak Sekili <buraksekili@gmail.com>
> fix: add certain chart version to unit-tests

- CHANGELOG.md
- tyk-headless/Chart.yaml
- tyk-headless/tests/deployment-gw-repset_test.yaml
- tyk-hybrid/Chart.yaml
- tyk-pro/Chart.yaml
> Updated changelog and prepared charts for v0.13.0

- CHANGELOG.md
- tyk-hybrid/configs/tyk_hybrid.conf
Enable `allow_explicit_policy_id` for hybrid by default
This flag is required if user is using operator with hybrid charts.
> [TT-7255] Enable allow_explicit_policy_id for hybrid

- .github/tyk_ce_values.yaml
- .github/tyk_hybrid_values.yaml
- .github/tyk_pro_values.yaml
- CHANGELOG.md
- tyk-headless/tests/deployment-gw-repset_test.yaml
- tyk-headless/values.yaml
- tyk-hybrid/values.yaml
- tyk-pro/values.yaml
Update component versions to following latest versions
- mdcb - 2.0.4
- gateway and dashboard - 4.3.1
- pump - 1.7.0
- tib - 1.3.1
[TT-7382](https://tyktech.atlassian.net/browse/TT-7382)
> [TT-7382] update components version

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
Resolves #256 
https://tyktech.atlassian.net/browse/TT-7510
> Remove include function from annotations

- .github/tyk_hybrid_values.yaml
- .github/tyk_pro_values.yaml
- tyk-hybrid/values.yaml
- tyk-pro/values.yaml
Changed default docker repository to cloudSmith for better tracking of image pulls.
> Changed docker repository  to cloudsmith

- tyk-pro/templates/deployment-mdcb.yaml
> [TT-5750] Add MDCB PGSQL support

- tyk-pro/templates/deployment-gw-repset.yaml
> fix extraVolumes for gateway deployment

- CHANGELOG.md
> Update changelog for the new release

- .github/tyk_pro_values.yaml
- .gitignore
- CHANGELOG.md
- tyk-pro/values.yaml
Update enterprise portal tag to v1.2.0
[TT-8508](https://tyktech.atlassian.net/browse/TT-8508)
Enterprise Portal v1.2+ is only supported by helm charts
Validated enterprise-portal v1.2.0 is installed successfully
[TT-8508]: https://tyktech.atlassian.net/browse/TT-8508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-8508] Update tag of enterprise portal

- tyk-headless/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-pmp.yaml
> [TT-8228] - Enable SSL for Uptime Mongo Pump if Mongo uses SSL

- .github/workflows/lint-test.yaml
- .github/workflows/smoke-lint-tests.yml
- .github/workflows/smoke-test.yml
- .github/workflows/unit-tests.yaml
**Update k8s version matrix**
- Run tests against k8s v1.26.3
- Remove k8s v1.19 from the test matrix
**Fixed unit tests workflow**
Latest version of `[helm-unittest](https://github.com/helm-unittest/helm-unittest)` has removed `-3` flag. Because of it unit-tests run command was failing.
[TT-8496](https://tyktech.atlassian.net/browse/TT-8496)
[TT-8496]: https://tyktech.atlassian.net/browse/TT-8496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-8496] Update k8s version matrix and fix unit tests workflow

- tyk-pro/templates/bootstrap-pre-delete.yaml
> [TT-9149] Changed ENV var to correct name (missing an underscore)

- tyk-pro/values.yaml
Fix https://github.com/TykTechnologies/tyk/issues/5064
> [TT-9147] fix bootstrap job name typo

- .github/workflows/lint-test.yaml
- .github/workflows/release-charts.yaml
- .github/workflows/smoke-lint-tests.yml
- .github/workflows/smoke-test.yml
- tyk-pro/templates/statefulset-enterprise-portal.yaml
Fix incorrect dashboard service url
> [TT-9093] Update statefulset-enterprise-portal.yaml

- tyk-headless/templates/deployment-gw-repset.yaml
> [TT-9148] Update deployment-gw-repset.yaml

- tyk-pro/templates/statefulset-enterprise-portal.yaml
Added a new volume mount to enable the enterprise developer portal to be installed/configured with sqlite
> TT-8937 Added edp sqlite persistent volume

- CHANGELOG.md
- tyk-headless/Chart.yaml
- tyk-hybrid/Chart.yaml
- tyk-pro/Chart.yaml
> Added v0.14.1 CHANGELOG.md

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/tests/deployment-gw-repset_test.yaml
> Fix setting of policy path environment variable

- CHANGELOG.md
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/bootstrap-pre-delete.yaml
- tyk-pro/values.yaml
Make bootstrap jobs image and tag configurable. Set to v1.5.1 by default.
[TT-10382](https://tyktech.atlassian.net/browse/TT-10382)
[TT-10382]: https://tyktech.atlassian.net/browse/TT-10382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10382] Make bootstrap jobs image and tag configurable

- CHANGELOG.md
- tyk-headless/tests/deployment-gw-repset_test.yaml
- tyk-headless/values.yaml
- tyk-hybrid/values.yaml
- tyk-pro/values.yaml
Updated components version to latest
[TT-10779](https://tyktech.atlassian.net/browse/TT-10779)
[TT-10779]: https://tyktech.atlassian.net/browse/TT-10779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10779] Updated component version to latest

- tyk-pro/templates/secret-certs.yaml
- tyk-pro/templates/secret-dashboard.yaml
- Create dashboard login secret only if dashboard deployment is enabled.
- Create tls-secret only if gateway/mdcb tls is enabled.
[TT-10152](https://tyktech.atlassian.net/browse/TT-10152)
- Verified dashboard secret is created only if dash.enabled is true.
- Verified default-cert secret is created only if tls for gateway/mdcb is enabled.
[TT-10152]: https://tyktech.atlassian.net/browse/TT-10152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10152] Create resources only if deployment of corresponding component is enabled

- CHANGELOG.md
- tyk-pro/templates/statefulset-enterprise-portal.yaml
- tyk-pro/values.yaml
Fixed probes path of enterprise portal. Update enterprise portal version to latest.
[TT-10732](https://tyktech.atlassian.net/browse/TT-10732)
[TT-10732]: https://tyktech.atlassian.net/browse/TT-10732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-10732] Fixed edp probes

- CHANGELOG.md
- tyk-headless/Chart.yaml
- tyk-hybrid/Chart.yaml
- tyk-pro/Chart.yaml
This PR updates manifests for v0.14.2 release
https://tyktech.atlassian.net/browse/TT-10507
> [TT-10507] Updates manifests for v0.14.2
