- tyk-pro/scripts/bootstrap_k8s.sh
- tyk-pro/templates/NOTES.txt
Use of `sed -i` has different syntax across operating systems. This fix redirects output of `sed` to new file rather than taking a copy of the template and modifying the copy in-line.
Tweaking NOTES.txt to put jsonpath in quotes and avoid having to escape. Resolves issue on OSX
fixed typo of file extension in NOTES.txt
> Typos n bugfixes

- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-pmp.yaml
Specifying resource requests and limits had no effect and some strings woudn't be properly set to the env vars.
> Fixes resource values reference and some strings not being quoted for the env vars

- README.md
Community edition was targeting `./tyk-pro`, when should be targeting `./tyk-headless`.
> Fix to target correct value files

- README.md
The readme said to install tyk-pro for community edition. This led to a failed install because of a missmatch between community values and pro install.
> Fixed copy paste typo for community install.

- .gitignore
- README.md
- tyk-headless/scripts/secret_tpl.yaml
- tyk-headless/templates/configmap-tyk-k8s.yaml
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-headless/templates/service-gw.yaml
- tyk-hybrid/templates/NOTES.txt
- tyk-hybrid/templates/configmap-tyk-k8s.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/service-gw.yaml
- tyk-k8s/templates/deployment-tyk-k8s.yaml
- tyk-k8s/templates/rbac.yaml
- tyk-pro/scripts/bootstrap_k8s.sh
- tyk-pro/templates/NOTES.txt
- tyk-pro/templates/configmap-tyk-k8s.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/templates/ingress-dash.yaml
- tyk-pro/templates/service-dash.yaml
- tyk-pro/templates/service-gw.yaml
- tyk-pro/templates/service-tib.yaml
- values.yaml
- values_community_edition.yaml
- values_hybrid.yaml
This updates resources all across the charts, which makes them work on k8s 1.16+.
Brings "tyk_k8s.watchNamespaces" array option to watch only specific namespaces in the ingress controller (depends on https://github.com/TykTechnologies/tyk-k8s/pull/30).
Simplifies ingress controller chart installation by not requiring certificate generation unless service mesh injector is required. Clarifies some instructions and readme too a bit.
Fixes RBAC in the ingress controller's cluster role.
Bootstrap script now works with Python 3.x.
> Updates resources, brings watchNamespaces, controller certs gen optional, fixes

- tyk-pro/templates/deployment-mdcb.yaml
Pod doesn't start with the '--conf' parameter and logs that it does not know the parameter but instead, it knows '--c'.
Log of the mdcb pod:
```
flag provided but not defined: -conf
Usage of /opt/tyk-sink/tyk-sink:
-c string
Path to the config file (default "./tyk_sink.conf")
-debug
Enable verbose output
```
> change command parameter

- README.md
Stable is deprecated in favour of bitnami. Functions exactly the same.
> Update redis and mongo charts

- README.md
Moved important notes to the top of the list from its current position as users may just want to test Tyk once the basic installation is provisioned.
> Moved important notes to the top

- tyk-k8s/templates/deployment-tyk-k8s.yaml
Don't need this, new `tyk-k8s` Dockerfile has embedded:
https://github.com/TykTechnologies/tyk-k8s/pull/43
> dont need these operands

- README.md
- tyk-hybrid/templates/ingress-gw.yaml
- tyk-k8s/tests/ingress/cafe.yaml
- tyk-k8s/tests/ingress/ingress.yaml
- tyk-pro/templates/ingress-dash.yaml
- tyk-pro/templates/ingress-gw.yaml
- tyk-pro/templates/ingress-portal.yaml
- tyk-pro/templates/ingress-tib.yaml
This PR updates `extensions/v1beta1` to use the proper non-deprecated/removed apiVersions for deployments and ingresses.
It also contains some formatting changes that make all the yaml formatted the same across the different files that I touched.
> update deprecated apiVersions

- tyk-hybrid/Chart.yaml
- tyk-hybrid/templates/ingress-gw.yaml
- tyk-hybrid/templates/service-gw.yaml
Update Hybrid gateway ingress resource to allow different gateway service ports being used. Atm we're allowing only http, which is causing issue, if you want to use https for example, hence the PR to extend this functionality. Also bump hybrid chart version.
> Update hybrid gateway ingress resource and bump hybrid chart version

- tyk-headless/Chart.yaml
- tyk-headless/configs/tyk_mgmt.conf
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-hybrid/Chart.yaml
- tyk-hybrid/configs/tyk_hybrid.conf
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-pro/Chart.yaml
- tyk-pro/configs/tyk_mgmt.conf
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
Changed the templates to run all Tyk containers as non-root user by default.
Also keeping an option to change the user for the gateway since there might be a use case where this would be needed.
Bumped chart version.
> Run containers as non-root by default

- README.md
- tyk-hybrid/Chart.yaml
- tyk-hybrid/configs/tyk_hybrid.conf
- tyk-hybrid/templates/deployment-gw-repset.yaml
- values_hybrid.yaml
Some improvements to docs and useability aimed at improving the get started journey for Tyk Cloud users.
- Move the RPC key and API key fields to the gateway RPC section
- insecure skip verify is default
- remove bindtoslugs
- move helm install command up and style like the others
- Change lb service to nodeport to match other charts
- add some helpful comments and an example config so that classic cloud users can keep using these charts
> Hybrid improvements

- tyk-headless/Chart.yaml
- tyk-headless/configs/tyk_mgmt.conf
- tyk-headless/templates/deployment-gw-repset.yaml
- values_community_edition.yaml
There are some weird things with the headless helm chart i'm trying to address.
1. Disable sharding and tags - with the OSS gateway the default behaviour is based around 1 GW so lets not introduce that complexity. Having it enabled is an artifact from the deprecated service mesh piece.
2. For some reason the chart assumes a mongo is deployed even though we say it is not necessary in the readme - this means we are harming gateway performance by producing analytics and either sending to Redis where it is purged or we send to a Mongo instance which relies on a Tyk Dashboard to visualise. Instead we should look at how to accommodate open source options for defaults in another PR. Suggestions welcome!
> OSS Deployment improvements

- tyk-hybrid/Chart.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- values_hybrid.yaml
We were getting the error 
Error: template: tyk-hybrid/templates/deployment-gw-repset.yaml:81:38: executing "tyk-hybrid/templates/deployment-gw-repset.yaml" at <.Values.tyk_k8s.org_id>: nil pointer evaluating interface {}.org_id
When running the chart because the default fallback is the old values for orgID and apiKey.
> Correct problems with chart start and missing deprecated values

- README.md
- samples/httpbin.yaml
- samples/istio/bookinfo.yaml
- tyk-pro/Chart.yaml
- tyk-pro/configs/tyk_mgmt.conf
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- values.yaml
Tyk can be situated at the edge of a service mesh as the ingress gateway.
These changes make it easy to use our helm charts for this purpose.
All that needs to be done to test is:
Install Istio on a cluster.
To use Tyks gateways as the ingress to your Istio Service Mesh simply change `enableIstioIngress: true` in the values.yaml. Ensure you are using an Istio manifest which disables the default Istio Ingress gateway.
There will be a docs guide shortly that goes through the whole process based on these changes and also includes using the operator.
Also have added some sample applications to reference from docs and guides.
Also change the gateway config so we are able to use tyk sync and the operator by default with the gateway.
> Istio Ingress Support

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
Fixes #84
Fixes checksum/config annotation to use correct config maps instead of self
referencing deployment (That was leading to recursion)
> [TD-37] Checksum configmaps

- tyk-headless/templates/deployment-gw-repset.yaml
Based on the solution proposed here https://github.com/TykTechnologies/tyk-helm-chart/pull/93#pullrequestreview-614090651
For tyk-headless deploying the chart and trying to create new api results in
the following error
```
Failed to create file! - open /mnt/tyk-gateway/apps/YmRkL3dvcmthcm91bmQtYXBp.json: no such file or directory
```
The gateway assumes `/mnt/tyk-gateway/apps` is a directory that already exists,
however we only mount `/mnt/tyk-gateway` which means we need to create `apps`
sub directory for thw gateway to work
This PR ensures that `apps`, `middleware` and `policies` directories are
properly created making the gateway happy when creating/updating and deleting
api's and policies
This used init container to setup the directories
> tyk-headless: Setup directories needed for tyk to be operational

- tyk-pro/templates/deployment-pmp.yaml
This change make sure that checksum/config is set even when
`.Values.pump.annotations` is not set
To reproduce the issue, just comment  `annotations` line in `pump` section of `values.yaml` this will create the pod without the checksum annotation.
> tyk-pro: ensure checksum/config for pump deployment is set

- README.md
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/ingress-portal.yaml
- tyk-pro/values.yaml
The Tyk Developer Portal `path` currently being read from the `tyk_analytics.conf`. This PR changes this in order to inject the portal path from the `values.yaml` into the Dashboard as an environment variable.
Also, I moved the `portal.ingress.path` to `portal.path` because the value applies to the Portal globally, even outside of any Ingress objects created.  Furthermore, there is a `portal.ingress.enabled` section which will be confusing if that is set to `false`, yet we are still injecting the `path` into an environment variable.
> injects portal path as config env variable into dashboard.

- tyk-pro/scripts/bootstrap.sh
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/bootstrap-role.yml
A couple of things i missed in #105. 
- Grant post-install hook job access to restart dashboard deployment
- Allow hooks to retry only once because if the job is retried number of times the script will bootstrap from scratch each time causing `ORG DATA: {"Status":"Error","Message":"Failed to save new Org object to DB","Meta":null}
ORG ID: null` error
- Use dashboard deployment name as an environment variable in the bootstrap script
> [TD-219] Tyk Pro bootstrap

- tyk-headless/Chart.yaml
- tyk-headless/values.yaml
- tyk-hybrid/Chart.yaml
- tyk-hybrid/values.yaml
- tyk-pro/Chart.yaml
- tyk-pro/configs/tyk_analytics.conf
- tyk-pro/scripts/bootstrap.sh
- tyk-pro/scripts/init.sh
- tyk-pro/scripts/wait-for-it.sh
- tyk-pro/templates/NOTES.txt
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/bootstrap-role-binding.yml
- tyk-pro/templates/bootstrap-role.yml
- tyk-pro/templates/bootstrap-service.yml
- tyk-pro/templates/configmap-dashboard.yaml
- tyk-pro/templates/configmap-gateway.yaml
- tyk-pro/templates/configmap-post-install-bootstrap.yaml
- tyk-pro/templates/configmap-pump.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/templates/ingress-dash.yaml
- tyk-pro/templates/ingress-gw.yaml
- tyk-pro/templates/ingress-portal.yaml
- tyk-pro/templates/service-dash.yaml
- tyk-pro/templates/service-gw-control.yaml
- tyk-pro/templates/service-gw.yaml
- tyk-pro/values.yaml
- Updated all default hostname values to mirror values used in the ingress section for the respective services. 
- Changed Gateway TLS to be disabled by default.
- Added the ability to disable Dashboard bootstrapping in the tyk-pro helm.
- Turned off the `use_sharded_analytics` option in the tyk-pro helm.
- Added the ability to disable different Tyk components in the tyk-pro helm.
- Added control API gateway functionality to the tyk-pro helm.
- Fixed bootstrap vs dashboard race issues. 
- Dynamically set dashboard URL protocol based on tls option under dash service in the tyk-pro helm.
Tickets resolved:
- https://tyktech.atlassian.net/browse/TD-251
> Helm updates

- .github/workflows/smoke-test.yml
You must create a secret named ACTIONS_STEP_DEBUG with the value true to see the debug messages set by this command in the log.
> For future debugging

- .github/tyk_ce_values.yaml
- .github/tyk_hybrid_values.yaml
- .github/tyk_pro_values.yaml
- .github/workflows/smoke-test.yml
- ct.yaml
- tyk-headless/Chart.yaml
- tyk-headless/templates/_helpers.tpl
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/values.yaml
- tyk-hybrid/Chart.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/values.yaml
- tyk-pro/Chart.yaml
- tyk-pro/templates/_helpers.tpl
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/values.yaml
Allow gateway liveness and readiness probe to query control-api when it's enabled. Also, the `/hello` endpoint might not be available on control api for specific versions so it checks for that and update the port accordingly.
> [TD-283] liveness and readiness probe to query control api

- .github/workflows/lint-test.yaml
- .github/workflows/smoke-test.yml
- .github/workflows/tests-pr.yml
Due to the limitation in #126, this PR allows to run smoke tests on Tyk Headless chart and lint all charts for every PR coming from branches or forks. Once we resolve on how to share secrets with workflows from forks, we can revert these changes.
Also, smoke tests and lint will run for all charts on master branch once PR is merged.
> [BUG] Disable running actions on pro and hybrid charts for PRs

- tyk-headless/Chart.yaml
- tyk-headless/README.md
- tyk-headless/templates/_helpers.tpl
- tyk-hybrid/Chart.yaml
- tyk-hybrid/README.md
- tyk-hybrid/values.yaml
- tyk-pro/Chart.yaml
- tyk-pro/README.md
- tyk-pro/templates/_helpers.tpl
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/values.yaml
1. add appVersion
2. remove the `mongo: {}` in tyk-pro/values.yaml since it's confusing. If you set the mongoURL because of the few comment lines you don't see that there're `{}` after `mongo` that needs to be deleted. Adding a single field with the default value sort this out
3. Wrong field name. We had "tag" for sharding the gateways instead of "tags". I tested it by copying the gateway section in values.yaml and deployment and service and saw that with "tags it works.
> Update instructions and appVersion

- tyk-headless/templates/deployment-gw-repset.yaml
Making this minor change, so that the user passing mount values from values.yaml file will be correctly mounted under the main container rather the initContainer since it goes off once the main container is initialized and the mounted secret becomes null.
> making user passed secrets mount in main container

- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-headless/templates/secrets.yaml
- tyk-headless/values.yaml
According to `NewRedisClusterPool`, different storage redis configuration will initialize different redis client:
* master_name != "", redis client will be `redis.NewFailoverClient`
* enable_cluster == true, redis client will be `redis.NewClusterClient`
* others condition, redis client will be `redis.NewClient`
Signed-off-by: Chenyang Yan <memory.yancy@gmail.com>
P.S.: if it's significant, I will also update `tyk-hybrid, tyk-pro` similar Redis configuration and rebase commit :smiley:.
CC: @kulong0105
> optimize storage redis configuration to support different mode

- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/values.yaml
Updated tyk-hybrid chart to support running multiple isolated gateway clusters using group_id, and fixes issue [193](https://github.com/TykTechnologies/tyk-helm-chart/issues/193)
> [TT-4979] added group_id to hybrid chart

- tyk-pro/scripts/init.sh
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/deployment-dash.yaml
This PR adds a validation on the environment configuration of the tyk-pro. 
- Checks if the DB License is empty, valid (of type `jwt`) or expired,
- Adds liveness check (using GW's `/hello` endpoint) for Gateway, Dashboard and Redis. If any of these are not ready, bootstrap won't start
Signed-off-by: Burak Sekili <buraksekili@gmail.com>
> [TT-5609] Check Environment Configuration Before Bootstrapping

- tyk-pro/scripts/bootstrap.sh
- tyk-pro/scripts/init.sh
- tyk-pro/scripts/pre-delete.sh
- tyk-pro/templates/NOTES.txt
- tyk-pro/templates/bootstrap-post-install.yaml
- tyk-pro/templates/bootstrap-pre-delete.yaml
- tyk-pro/templates/bootstrap-role.yml
- tyk-pro/templates/configmap-pre-delete.yaml
- tyk-pro/values.yaml
Current problem observed:
- `tyk-operator-conf` is not deleted if we do helm delete
- Failed Job doesn’t get deleted if we do helm delete. We end up with more jobs that fail
This PR adds 
- `before-hook-creation` to the delete policy of the post-install bootstrap. So that, jobs created by the bootstrap will be deleted either before a new hook is launched or successfully finished.
- new deletion hooks to clean up a secret of tyk-operator if it exists.
- new field called `operatorSecret` in the values.yaml. If it is set to true, `tyk-operator-conf` is created along with the dashboard bootstrap. Otherwise, it won't be created.
> [TT-5524] Update bootstrap post-install hook and introduce new field in the values.yaml

- tyk-headless/README.md
Signed-off-by: Burak Sekili <buraksekili@gmail.com>
This PR updates the headless chart's README to indicate the required steps to configure the Gateway deployment type.
By default, gateway is deployed as DaemonSet. Users might want to change it to Deployment type while using a multi-node environment for their headless GW. This PR adds instructions to show how to do required changes in the headless chart.
> TT-6100 Update tyk-headless docs on Tyk GW deployment type

- .github/CODEOWNERS
We are renaming github team name from tyk-operator to operator-squad.
Replacing all the references of it in the repo.
> Rename team name

- CHANGELOG.md
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/deployment-pmp.yaml
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-dash.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/templates/statefulset-enterprise-portal.yaml
Currently, if you update secrets in from the values.yaml that does not trigger deployment updates. Adding the secrets hashes to the deployment annotation seems to be the recommended approach to solving this issue per helm chart docs
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
> TT-7026 Add secret hashes

- tyk-pro/templates/deployment-gw-repset.yaml
- tyk-pro/templates/deployment-mdcb.yaml
- tyk-pro/templates/deployment-pmp.yaml
- tyk-pro/templates/deployment-tib.yaml
- tyk-pro/templates/statefulset-enterprise-portal.yaml
Currently if we try to set an extraEnv that is a bool variable the helm charts will fail...
`failed to create resource: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
Such sets will fail...
--set "mdcb.extraEnvs[0].name=TYK_MDCB_SYNCWORKER_ENABLED" \
--set "mdcb.extraEnvs[0].value=true" \
--set "mdcb.extraEnvs[1].name=TYK_MDCB_SYNCWORKER_HASHKEYS" \
--set "mdcb.extraEnvs[1].value=true" \
> TT-7028 Fix support for bool values

- .github/workflows/smoke-lint-tests.yml
- .github/workflows/tests-pr.yml
- .github/workflows/unit-tests.yaml
- tyk-headless/.helmignore
- tyk-headless/tests/deployment-gw-repset_test.yaml
This PR adds unit tests for tyk-headless gw component using [helm-unittest](https://github.com/quintush/helm-unittest/)framework
> [TT-7010] - Add unit tests

- tyk-hybrid/templates/_helpers.tpl
- tyk-hybrid/templates/deployment-gw-repset.yaml
- tyk-hybrid/values.yaml
- tyk-pro/templates/deployment-gw-repset.yaml
Added the modifications proposed in this [pull request ](https://github.com/TykTechnologies/tyk-helm-chart/pull/244) on all Tyk helm charts.
> Fix probes v4 extended

- CHANGELOG.md
- tyk-headless/templates/_helpers.tpl
- tyk-headless/templates/deployment-gw-repset.yaml
- tyk-headless/templates/secrets.yaml
Validate `redis` and `mongo` fields are not nil before accessing it's child fields
[TT-7211](https://tyktech.atlassian.net/browse/TT-7211)
Installation was successful with empty `mongo` and `redis` fields.
> [TT-7211] Fix headless templates

- tyk-pro/values.yaml
The job that runs bootstrapping includes a minor typo. This PR updates the typo.
> Fix typos in bootstrap job name for tyk-pro

- .github/tyk_hybrid_values.yaml
- .github/tyk_pro_values.yaml
- tyk-hybrid/values.yaml
- tyk-pro/values.yaml
> Update default image repositories of tyk-pro and tyk-hybrid

- CHANGELOG.md
- tyk-pro/templates/statefulset-enterprise-portal.yaml
- tyk-pro/values.yaml
- Changed default initialDelaySeconds for probes of enterprise portal to 60s
- Made it configurable.
[TT-9165](https://tyktech.atlassian.net/browse/TT-9165)
[TT-9165]: https://tyktech.atlassian.net/browse/TT-9165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TT-9165] Make initialDelaySeconds configurable for enterprise portal
